spring.datasource.url=jdbc:mysql://localhost:3306/staff-management-db
spring.datasource.username=root
spring.datasource.password=Sanjiv

//
swagger.enabled=false
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false

