spring.datasource.url=jdbc:mysql://localhost:3306/staff-management-db
spring.datasource.username=root
spring.datasource.password=Sanjiv

swagger.enabled=true
springdoc.swagger-ui.enabled= true 
springdoc.api-docs.enabled= true
